version: "3"
services:
  app:
    restart: on-failure
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
      - restpsql:/var/lib/postgresql/data

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rest

volumes:
  restpsql:
    external: true
